<a href="https://colab.research.google.com/github/jcmachicao/gdmk_tools_ml/blob/main/gdmk__cross_val_distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X_np = np.array([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 4, 4],
  [5, 5, 5, 5],

  [6, 6, 6, 6],
  [7, 7, 7, 7],
  [8, 8, 8, 8],
  [9, 9, 9, 9],
  [0, 0, 0, 0],               
])

X_np

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9],
       [0, 0, 0, 0]])

In [3]:
y_np = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
y_np

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
n_obs = X_np.shape[0]
n_obs

10

In [5]:
partes = 5
particion = int(n_obs/partes)
particion

2

In [6]:
parts = []

for kp in range(0,partes):
  print(kp, end=' ')
  
  if kp < 4:

    print( (kp-4)*particion ,  (kp)*particion)
    X_atr = np.concatenate( [ X_np[ (kp-4)*particion : , : ], X_np[ : (kp)*particion, : ] ], axis=0)
    X_ats = X_np[ (kp)*particion : (kp+1)*particion, : ]
    y_atr = np.concatenate( [ y_np[ (kp-4)*particion :], y_np[ : (kp)*particion] ], axis=0)
    y_ats = y_np[ (kp)*particion : (kp+1)*particion ]

  else:

    X_atr = X_np[ 0 : (kp)*particion, : ]
    X_ats = X_np[ (kp)*particion : (kp+1)*particion, : ]
    y_atr = y_np[  0 : (kp)*particion ]
    y_ats = y_np[ (kp)*particion : (kp+1)*particion ]

  parts.append([X_atr, X_ats, y_atr, y_ats]) 

0 -8 0
1 -6 2
2 -4 4
3 -2 6
4 

In [8]:
for s in range(5):
  for j in range(4):
    print(parts[s][j])
    print('')

[[3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]
 [9 9 9 9]
 [0 0 0 0]]

[[1 1 1 1]
 [2 2 2 2]]

[13 14 15 16 17 18 19 20]

[11 12]

[[5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]
 [9 9 9 9]
 [0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

[[3 3 3 3]
 [4 4 4 4]]

[15 16 17 18 19 20 11 12]

[13 14]

[[7 7 7 7]
 [8 8 8 8]
 [9 9 9 9]
 [0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

[[5 5 5 5]
 [6 6 6 6]]

[17 18 19 20 11 12 13 14]

[15 16]

[[9 9 9 9]
 [0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]

[[7 7 7 7]
 [8 8 8 8]]

[19 20 11 12 13 14 15 16]

[17 18]

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]

[[9 9 9 9]
 [0 0 0 0]]

[11 12 13 14 15 16 17 18]

[19 20]

